[settings]
agent_id = "mbg206/emerald-t2-myst"
name = "Emerald T2-Myst"
loadout_file = "loadouts/base_loadout.toml"
logo_file = "logos/logo_2.png"
run_command = "..\\venv\\Scripts\\python src\\bot.py t2-myst"
run_command_linux = "../venv/bin/python src/bot.py t2-myst"
hivemind = true

[details]
description = "Emerald test 2"
fun_fact = "where did this checkpoint come from???"
source_link = ""
developer = "mbg206 / l1ghtn1ng__"
language = "rlgym-v2"
tags = ["1v1"]