[settings]
agent_id = "mbg206/emerald-t3-e"
name = "Emerald T3-E"
loadout_file = "loadouts/base_loadout.toml"
logo_file = "logos/logo_3.png"
run_command = "..\\venv\\Scripts\\python src\\bot.py t3-e"
run_command_linux = "../venv/bin/python src/bot.py t3-e"
hivemind = true

[details]
description = "Emerald test 3"
fun_fact = "flip reset test 1"
source_link = ""
developer = "mbg206 / l1ghtn1ng__"
language = "rlgym-v2"
tags = ["1v1"]