[settings]
agent_id = "mbg206/emerald-t5.1"
name = "Emerald T5.1"
loadout_file = "loadouts/base_loadout.toml"
logo_file = "logos/logo_3.png"
run_command = "..\\venv\\Scripts\\python src\\bot.py t5.1"
run_command_linux = "../venv/bin/python src/bot.py t5.1"
hivemind = true

[details]
description = "Emerald test 5"
fun_fact = "rlgm-learny"
source_link = ""
developer = "mbg206 / l1ghtn1ng__"
language = "rlgym-v2"
tags = ["1v1", "teamplay"]